### ISSUE TITLE
Create instructor module

### ISSUE THREAD

**Issue by abhiteja29** [abhiteja29/mvc-app#2]

**Comment by yugimamidi** [comment]
- [ ] creating the model (and properties)
- [ ] creating sample data that fits the model
- [ ] seeding your sample data
- [ ] routing requests to your controller
- [ ] implementing your controller (2 json calls, 5 view requests, 3 data actions (create/update/delete)
- [ ] implementing implementing the five views used to listall/create/read/update/delete (CRUD).
- [ ] update the application navigation to provide access to your resource
- [ ] update the application navigation to provide access to your developer page.
