### ISSUE TITLE
Create section module

### ISSUE THREAD

**Issue by abhiteja29** [abhiteja29/mvc-app#4]

**Comment by bharat-reddy-male** [comment]
[ ] creating the model (and properties),
 [ ]creating sample data that fits the model,
 [ ]seeding your sample data
 [ ]routing requests to your controller
 [ ]implementing your controller (2 json calls, 5 view requests, 3 data actions (create/update/delete)
 [ ]implementing implementing the five views used to listall/create/read/update/delete (CRUD).
 [ ]update the application navigation to provide access to your resource
 [ ]update the application navigation to provide access to your developer page.

**Comment by bharat-reddy-male** [comment]
MVC app created and deployed
